language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - export DJANGO_SETTINGS_MODULE=celery_haystack.test_settings
install:
  - pip install -e .
  - pip install -r requirements/v2.txt $DJANGO
before_script:
  - flake8 celery_haystack --ignore=E501
script:
  - coverage run --branch --source=celery_haystack `which django-admin.py` test celery_haystack
  - coverage report --omit=celery_haystack/test*
env:
  - DJANGO="Django==1.8.7"
  - DJANGO="Django==1.9"
matrix:
  exclude:
  - env: DJANGO="Django==1.9"
    python: "3.3"
